### ISSUE TITLE
onClick(SpotXAd ad) event control

### ISSUE THREAD

**Issue by suhail-mir** [spotxmobile/spotx-demo-android#9]
Hi, I have integrated SPOTX sample and working perfect. But how to handle onClick(SpotXAd ad) event when Video Ad is loaded. Its everytime taking me to spotx site when add is clicked.

**Comment by scottjulian** [comment]
For the default channel used in the demo, "85394", this is the expected behavior. The clickthrough will always open the clickthrough URL in a safari web view that is given by the VAST, and you cannot override this behavior. The `onClick` event is simply for posterity so you know when this event has occurred.

**Comment by suhail-mir** [comment]
Thank you @scottjulian. We have got the working channel id. I hope we can configure this behaviour with that.

**Comment by ummerakbar45** [comment]
Hi @scottjulian 
I am also not able to handle this event,please tell me how to disable click event. I dont want any action on click, how to do?
